services:
  db:
    image: postgres:latest
    container_name: pontential-crud-backend-db
    restart: always
    environment:
      POSTGRES_PASSWORD: R@m_ryCnZH3pithzvExL
      POSTGRES_DB: gazin_core
      POSTGRES_PORT: '5432'
    ports:
      - '5432:5432'

  laravel:
    container_name: pontential-crud-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      COMPOSER_ALLOW_SUPERUSER: '1'

