services:
    db:
        image: postgres:latest
        container_name: db
        restart: always
        environment:
            POSTGRES_PASSWORD: R@m_ryCnZH3pithzvExL
            POSTGRES_DB: gazin_core
            POSTGRES_PORT: '5432'
        ports:
            - '5432:5432'
        volumes:
            - .docker/postgres-data:/var/lib/postgresql/data

    backend-app:
        container_name: backend-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:80'
        volumes:
            - .docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - db
        environment:
            COMPOSER_ALLOW_SUPERUSER: '1'

